# Generated by Django 5.1.3 on 2025-01-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalorderdish",
            old_name="dish",
            new_name="id_dish",
        ),
        migrations.RenameField(
            model_name="orderdish",
            old_name="dish",
            new_name="id_dish",
        ),
    ]
