# Generated by Django 5.1.3 on 2025-01-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_rename_dish_historicalorderdish_id_dish_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courier",
            options={"verbose_name": "Курьер", "verbose_name_plural": "Курьеры"},
        ),
        migrations.AlterModelOptions(
            name="historicalcourier",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Курьер",
                "verbose_name_plural": "historical Курьеры",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalorder",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Заказ",
                "verbose_name_plural": "historical Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalorderdish",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Заказанное блюдо",
                "verbose_name_plural": "historical Заказанные блюда",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrestaurant",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Ресторан",
                "verbose_name_plural": "historical Рестораны",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrestaurantdish",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Блюдо",
                "verbose_name_plural": "historical Блюда",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrestaurantgroup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Группа блюд",
                "verbose_name_plural": "historical Группы блюд",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalticket",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Тикет",
                "verbose_name_plural": "historical Тикеты",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaluseraddress",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Адрес пользователя",
                "verbose_name_plural": "historical Адреса пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterModelOptions(
            name="orderdish",
            options={
                "verbose_name": "Заказанное блюдо",
                "verbose_name_plural": "Заказанные блюда",
            },
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={
                "ordering": ["title"],
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
            },
        ),
        migrations.AlterModelOptions(
            name="restaurantdish",
            options={"verbose_name": "Блюдо", "verbose_name_plural": "Блюда"},
        ),
        migrations.AlterModelOptions(
            name="restaurantgroup",
            options={
                "verbose_name": "Группа блюд",
                "verbose_name_plural": "Группы блюд",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "Тикет", "verbose_name_plural": "Тикеты"},
        ),
        migrations.AlterModelOptions(
            name="useraddress",
            options={
                "verbose_name": "Адрес пользователя",
                "verbose_name_plural": "Адреса пользователей",
            },
        ),
        migrations.AddField(
            model_name="historicalorderdish",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
        migrations.AddField(
            model_name="orderdish",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
    ]
