# Generated by Django 5.1.3 on 2025-01-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_alter_courier_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="dishes",
            field=models.ManyToManyField(
                through="delivery.OrderDish", to="delivery.restaurantdish"
            ),
        ),
    ]
