# Generated by Django 5.1.3 on 2025-01-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_order_dishes"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="current_cart",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="current_cart",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
