# Generated by Django 5.1.3 on 2024-12-04 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_restaurantgroup_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdish',
            name='id_restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurant', verbose_name='ID ресторана'),
            preserve_default=False,
        ),
    ]
