# Generated by Django 5.1.3 on 2024-12-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_restaurantdish_id_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantdish',
            name='id_restaurant',
        ),
    ]
