# Generated by Django 5.1.3 on 2025-01-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0006_alter_historicalorder_id_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="couriers/"),
        ),
        migrations.AddField(
            model_name="courier",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcourier",
            name="resume",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalcourier",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
