# Generated by Django 5.1.3 on 2025-01-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "delivery",
            "0007_courier_resume_courier_url_historicalcourier_resume_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="courier",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="couriers/", verbose_name="Резюме"
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Соцсеть для связи"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcourier",
            name="resume",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Резюме"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcourier",
            name="url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Соцсеть для связи"
            ),
        ),
    ]
