# Generated by Django 5.1.3 on 2025-01-19 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0009_alter_restaurant_options_courier_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluseraddress",
            name="id_user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="id_user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="delivery.useraddress",
                verbose_name="ID адреса доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id_courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="delivery.courier",
                verbose_name="ID курьера",
            ),
        ),
        migrations.AlterField(
            model_name="orderattribute",
            name="id_attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_attributes",
                to="delivery.restaurantattribute",
                verbose_name="ID атрибута",
            ),
        ),
        migrations.AlterField(
            model_name="orderattribute",
            name="id_dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_attributes",
                to="delivery.orderdish",
                verbose_name="ID блюда в заказе",
            ),
        ),
        migrations.AlterField(
            model_name="orderdish",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_dishes",
                to="delivery.restaurantdish",
                verbose_name="ID блюда",
            ),
        ),
        migrations.AlterField(
            model_name="orderdish",
            name="id_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_dishes",
                to="delivery.order",
                verbose_name="ID заказа",
            ),
        ),
        migrations.AlterField(
            model_name="restaurantattribute",
            name="id_dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="delivery.restaurantdish",
                verbose_name="ID блюда",
            ),
        ),
        migrations.AlterField(
            model_name="restaurantdish",
            name="id_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="delivery.restaurantgroup",
                verbose_name="ID группы",
            ),
        ),
        migrations.AlterField(
            model_name="restaurantgroup",
            name="id_restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="delivery.restaurant",
                verbose_name="ID ресторана",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="id_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="delivery.order",
                verbose_name="ID заказа",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalUser",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
