# Generated by Django 5.1.3 on 2025-01-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0009_historicalrestaurant_slug_restaurant_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrestaurantgroup",
            name="slug",
            field=models.SlugField(
                default="None", max_length=64, verbose_name="Ссылка"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurantgroup",
            name="slug",
            field=models.SlugField(
                default="None", max_length=64, verbose_name="Ссылка"
            ),
            preserve_default=False,
        ),
    ]
