# Generated by Django 5.1.3 on 2025-01-19 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0010_alter_historicaluseraddress_id_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="date_created",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="date_updated",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalrestaurantdish",
            name="date_created",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalrestaurantdish",
            name="date_updated",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="date_updated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="restaurantdish",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurantdish",
            name="date_updated",
            field=models.DateField(auto_now=True),
        ),
    ]
