# Generated by Django 5.1.3 on 2025-01-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0010_historicalrestaurantgroup_slug_restaurantgroup_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrestaurantdish",
            name="pic",
            field=models.TextField(
                default="none", max_length=100, verbose_name="Фотография"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurantdish",
            name="pic",
            field=models.ImageField(
                default="none", upload_to="dishes/", verbose_name="Фотография"
            ),
            preserve_default=False,
        ),
    ]
