# Generated by Django 5.1.3 on 2025-01-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0011_historicalorder_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrestaurant",
            name="logo",
            field=models.TextField(default=0, max_length=100, verbose_name="Логотип"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="logo",
            field=models.ImageField(
                default=0, upload_to="uploads/", verbose_name="Логотип"
            ),
            preserve_default=False,
        ),
    ]
