# Generated by Django 5.1.3 on 2025-01-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0011_historicalrestaurantdish_pic_restaurantdish_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrestaurantdish",
            name="published",
            field=models.BooleanField(default=True, verbose_name="В открытом доступе"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurantdish",
            name="published",
            field=models.BooleanField(default=True, verbose_name="В открытом доступе"),
            preserve_default=False,
        ),
    ]
