# Generated by Django 5.1.3 on 2025-01-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0012_historicalrestaurantdish_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrestaurantdish",
            name="slug",
            field=models.SlugField(
                default="None", max_length=64, verbose_name="Ссылка"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurantdish",
            name="slug",
            field=models.SlugField(
                default="None", max_length=64, verbose_name="Ссылка"
            ),
            preserve_default=False,
        ),
    ]
