# Generated by Django 5.1.3 on 2025-01-19 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0012_historicalrestaurant_logo_restaurant_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courier",
            options={"verbose_name_plural": "Курьеры"},
        ),
        migrations.AlterModelOptions(
            name="historicalcourier",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical courier",
                "verbose_name_plural": "historical Курьеры",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalorder",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical order",
                "verbose_name_plural": "historical Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalorderattribute",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical order attribute",
                "verbose_name_plural": "historical Атрибуты заказанных блюд",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalorderdish",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical order dish",
                "verbose_name_plural": "historical Заказанные блюда",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrestaurant",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical restaurant",
                "verbose_name_plural": "historical Рестораны",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrestaurantattribute",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical restaurant attribute",
                "verbose_name_plural": "historical Атрибуты блюд",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrestaurantdish",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical restaurant dish",
                "verbose_name_plural": "historical Блюда",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrestaurantgroup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical restaurant group",
                "verbose_name_plural": "historical Группы блюд",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalticket",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ticket",
                "verbose_name_plural": "historical Тикеты",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaluseraddress",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical user address",
                "verbose_name_plural": "historical Адреса пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name_plural": "Заказы"},
        ),
        migrations.AlterModelOptions(
            name="orderattribute",
            options={"verbose_name_plural": "Атрибуты заказанных блюд"},
        ),
        migrations.AlterModelOptions(
            name="orderdish",
            options={"verbose_name_plural": "Заказанные блюда"},
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={"ordering": ["title"], "verbose_name_plural": "Рестораны"},
        ),
        migrations.AlterModelOptions(
            name="restaurantattribute",
            options={"verbose_name_plural": "Атрибуты блюд"},
        ),
        migrations.AlterModelOptions(
            name="restaurantdish",
            options={"verbose_name_plural": "Блюда"},
        ),
        migrations.AlterModelOptions(
            name="restaurantgroup",
            options={"verbose_name_plural": "Группы блюд"},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name_plural": "Тикеты"},
        ),
        migrations.AlterModelOptions(
            name="useraddress",
            options={"verbose_name_plural": "Адреса пользователей"},
        ),
        migrations.AddField(
            model_name="historicalrestaurantdish",
            name="date_published",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Дата опубликования",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurantdish",
            name="date_published",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата опубликования",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="date_created",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="date_updated",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Дата изменения"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrestaurantdish",
            name="date_created",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrestaurantdish",
            name="date_updated",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Дата изменения"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_created",
            field=models.DateField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_updated",
            field=models.DateField(auto_now=True, verbose_name="Дата изменения"),
        ),
        migrations.AlterField(
            model_name="restaurantdish",
            name="date_created",
            field=models.DateField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="restaurantdish",
            name="date_updated",
            field=models.DateField(auto_now=True, verbose_name="Дата изменения"),
        ),
    ]
