# Generated by Django 5.1.3 on 2025-01-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0014_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalrestaurantdish",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="restaurantdish",
            name="slug",
        ),
    ]
