services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web
  celery:
     build: .
     command: celery -A main worker -l info
     environment:
      - DJANGO_SETTINGS_MODULE=main.settings