services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
      - mailhog
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web
  redis:
    image: redis:alpine
  celery:
     build: .
     command: celery -A main worker -l info
     depends_on:
      - redis
     environment:
      - DJANGO_SETTINGS_MODULE=main.settings
  celery-beat:
     build: .
     command: celery -A main beat -l info
     depends_on:
      - redis
      - web
     environment:
      - DJANGO_SETTINGS_MODULE=main.settings