# Generated by Django 5.1.3 on 2024-12-01 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserPays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=8)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dishattributes')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orderdishes')),
            ],
        ),
        migrations.AddField(
            model_name='orderdishes',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orders'),
        ),
        migrations.AddField(
            model_name='orderdishes',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurantdishes'),
        ),
        migrations.AddField(
            model_name='dishattributes',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurantdishes'),
        ),
        migrations.AddField(
            model_name='restaurantdishes',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurantgroups'),
        ),
        migrations.AddField(
            model_name='restaurantgroups',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurants'),
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.useraddresses'),
        ),
        migrations.AddField(
            model_name='orders',
            name='pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpays'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userroles')),
            ],
        ),
        migrations.AddField(
            model_name='userpays',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
        migrations.AddField(
            model_name='orders',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier', to='main.users'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.users'),
        ),
    ]
